"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Mic, MicOff, Send } from "lucide-react";
import { api, Student } from "@/lib/api";
import { useUiStore } from "@/lib/store";

type Message={role:"me"|"ai";text:string};
type VoiceState="IDLE"|"LISTENING"|"UPLOADING"|"THINKING"|"SPEAKING";
type VoiceTurn={transcript:string;decision:{reply:string};audio:{url:string}|null;audio_error?:{message:string}};

export default function Tutor(){
  const students=useQuery({queryKey:["students"],queryFn:()=>api<Student[]>("/students")});
  const selected=useUiStore(s=>s.studentId)||students.data?.[0]?.id;
  const sessionRef=useRef<string|null>(null);
  const [messages,setMessages]=useState<Message[]>([{role:"ai",text:"Hello! I'm Emma. What are you learning today?"}]);
  const [voiceState,setVoiceState]=useState<VoiceState>("IDLE"); const [notice,setNotice]=useState("");
  const [voiceActive,setVoiceActive]=useState(false);
  const active=useRef(false), stream=useRef<MediaStream|null>(null), recorder=useRef<MediaRecorder|null>(null), context=useRef<AudioContext|null>(null), animation=useRef<number|null>(null), playback=useRef<HTMLAudioElement|null>(null), discard=useRef(false);

  async function ensureSession(){if(sessionRef.current)return sessionRef.current;const started=await api<{id:string}>("/sessions",{method:"POST",body:JSON.stringify({student_id:selected,mode:"lesson"})});sessionRef.current=started.id;return started.id}
  function releaseInput(){if(animation.current!==null)cancelAnimationFrame(animation.current);animation.current=null;if(recorder.current?.state==="recording"){discard.current=true;recorder.current.stop()}recorder.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;context.current?.close();context.current=null}
  function finishUtterance(){if(recorder.current?.state==="recording")recorder.current.stop()}
  function stopConversation(){active.current=false;setVoiceActive(false);releaseInput();playback.current?.pause();playback.current=null;setVoiceState("IDLE");setNotice("语音对话已结束")}
  async function playReply(url:string|null){releaseInput();if(!url){setVoiceState("IDLE");if(active.current)setTimeout(startListening,300);return}setVoiceState("SPEAKING");const player=new Audio(url);playback.current=player;player.onended=()=>{playback.current=null;if(active.current)setTimeout(startListening,300);else setVoiceState("IDLE")};player.onerror=()=>{setNotice("语音播放失败，已保留文字回复");if(active.current)setTimeout(startListening,300)};await player.play().catch(()=>player.onerror?.(new Event("error")))}
  async function sendVoice(blob:Blob){if(!active.current)return;setVoiceState("UPLOADING");setNotice("正在识别…");try{const id=await ensureSession();setVoiceState("THINKING");const form=new FormData();form.append("session_id",id);form.append("language","en");form.append("learning_context",JSON.stringify({scenario:"同步巩固",available_minutes:15}));form.append("audio",blob,"speech.webm");const result=await api<VoiceTurn>("/tutor/voice-turn",{method:"POST",body:form});setMessages(x=>[...x,{role:"me",text:result.transcript},{role:"ai",text:result.decision.reply}]);setNotice(result.audio_error?.message||"");await playReply(result.audio?.url||null)}catch(error){setNotice(error instanceof Error?error.message:"语音对话失败");if(active.current)setTimeout(startListening,800);else setVoiceState("IDLE")}}
  async function startListening(){if(!active.current||recorder.current?.state==="recording")return;try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")throw new Error("当前浏览器不支持录音，请使用最新版 Chrome、Edge 或 Safari");const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=media;const AudioCtor=window.AudioContext||window.webkitAudioContext;const audioContext=new AudioCtor();context.current=audioContext;const analyser=audioContext.createAnalyser();analyser.fftSize=1024;audioContext.createMediaStreamSource(media).connect(analyser);const mime=["audio/webm;codecs=opus","audio/webm","audio/mp4"].find(x=>MediaRecorder.isTypeSupported(x));const mediaRecorder=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=mediaRecorder;const chunks:BlobPart[]=[];discard.current=false;mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=()=>{releaseInput();if(!discard.current&&chunks.length)sendVoice(new Blob(chunks,{type:mediaRecorder.mimeType||"audio/webm"}))};mediaRecorder.start(250);setVoiceState("LISTENING");setNotice("请说话，停顿后会自动发送；也可手动发送本句");const samples=new Uint8Array(analyser.fftSize);const startedAt=performance.now();let heard=false,silentSince=0,warned=false;const detect=()=>{if(mediaRecorder.state!=="recording")return;analyser.getByteTimeDomainData(samples);let sum=0;for(const value of samples){const sample=(value-128)/128;sum+=sample*sample}const rms=Math.sqrt(sum/samples.length);const now=performance.now();if(rms>.025){heard=true;silentSince=0}else if(heard&&!silentSince)silentSince=now;if(heard&&silentSince&&now-silentSince>1200){mediaRecorder.stop();return}if(now-startedAt>30000){mediaRecorder.stop();return}if(!heard&&now-startedAt>10000&&!warned){warned=true;setNotice("还没听到声音，请靠近麦克风说话")}animation.current=requestAnimationFrame(detect)};detect()}catch(error){active.current=false;setVoiceActive(false);releaseInput();setVoiceState("IDLE");setNotice(error instanceof Error?`无法使用麦克风：${error.message}`:"无法使用麦克风")}}
  async function beginConversation(){if(!selected)return;active.current=true;setVoiceActive(true);setNotice("");await startListening()}
  async function sendText(text:string){const id=await ensureSession();setMessages(x=>[...x,{role:"me",text}]);setVoiceState("THINKING");const result=await api<{reply:string}>("/tutor/message",{method:"POST",body:JSON.stringify({session_id:id,text,learning_context:{scenario:"同步巩固",available_minutes:15}})});setMessages(x=>[...x,{role:"ai",text:result.reply}]);const form=new FormData();form.append("text",result.reply);form.append("voice","Emma");const speech=await api<{url:string}>("/audio/speech",{method:"POST",body:form}).catch(()=>null);await playReply(speech?.url||null)}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const text=String(new FormData(form).get("text")||"").trim();if(!text)return;form.reset();try{await sendText(text)}catch(error){setNotice(error instanceof Error?error.message:"发送失败");setVoiceState("IDLE")}}
  useEffect(()=>{if(sessionRef.current){active.current=false;setVoiceActive(false);releaseInput();sessionRef.current=null;setVoiceState("IDLE")}},[selected]);
  useEffect(()=>()=>{active.current=false;releaseInput();playback.current?.pause()},[]);
  return <section className="card"><h1>AI 老师 Emma</h1><p className="muted">Emma 会结合服务端记录的年级、当前课程、掌握度和错题进行辅导。</p><div className="row"><button onClick={voiceActive?stopConversation:beginConversation} disabled={!selected||(!voiceActive&&voiceState!=="IDLE")}>{voiceActive?<><MicOff/>结束语音对话</>:<><Mic/>开始语音对话</>}</button>{voiceState==="LISTENING"&&<button className="secondary" onClick={finishUtterance}>发送本句</button>}<span className={`voice-state state-${voiceState.toLowerCase()}`}>{voiceState}</span></div>{notice&&<p className="feedback">{notice}</p>}<div className="chat">{messages.map((m,i)=><div key={i} className={`bubble ${m.role==="me"?"me":""}`}>{m.text}</div>)}</div><form className="row" onSubmit={submit}><input style={{flex:1}} name="text" disabled={voiceState!=="IDLE"} placeholder="用英语或中文告诉 Emma…"/><button disabled={!selected||voiceState!=="IDLE"}><Send/>发送</button></form></section>
}

declare global { interface Window { webkitAudioContext: typeof AudioContext } }
