"""initial schema

Revision ID: d06d8292e4e4
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'd06d8292e4e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('voice', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_assets_cache_key'), ['cache_key'], unique=True)

    op.create_table('families',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=30), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_subject_id'), ['subject_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_family_id'), ['family_id'], unique=False)

    op.create_table('knowledge_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_subject_id'), ['subject_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_family_id'), ['family_id'], unique=False)

    op.create_table('textbook_editions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=30), nullable=False),
    sa.Column('source_commit', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('textbook_editions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_textbook_editions_subject_id'), ['subject_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('refresh_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_family_id'), ['family_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_sessions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_sessions_subject_id'), ['subject_id'], unique=False)

    op.create_table('masteries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('knowledge_point_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('difficult_streak', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point_id', name='uq_mastery')
    )
    with op.batch_alter_table('masteries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masteries_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_masteries_student_id'), ['student_id'], unique=False)

    op.create_table('mistakes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('knowledge_point_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mistake_type', sa.String(length=80), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point_id', 'content', name='uq_mistake')
    )
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mistakes_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_subject_id'), ['subject_id'], unique=False)

    op.create_table('review_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('knowledge_point_id', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_student_id'), ['student_id'], unique=False)

    op.create_table('textbook_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('printed_page', sa.String(length=20), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('web_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['textbook_editions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'position', name='uq_edition_page')
    )
    with op.batch_alter_table('textbook_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_textbook_pages_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_textbook_pages_sha256'), ['sha256'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_course_id'), ['course_id'], unique=False)

    op.create_table('vocabulary_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_items_student_id'), ['student_id'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learning_session_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learning_session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_session_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_unit_id'), ['unit_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.Column('knowledge_point_id', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(length=150), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('lesson_page_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('start_page_id', sa.String(), nullable=False),
    sa.Column('end_page_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['end_page_id'], ['textbook_pages.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['start_page_id'], ['textbook_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_page_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_page_links_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('passages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('passages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passages_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('utterances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('asr_text', sa.Text(), nullable=True),
    sa.Column('audio_asset_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utterances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utterances_conversation_session_id'), ['conversation_session_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=True),
    sa.Column('knowledge_point_id', sa.String(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('hint_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('passage_sentences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('passage_id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('audio_asset_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['textbook_pages.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_id', 'position', name='uq_passage_sentence')
    )
    with op.batch_alter_table('passage_sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passage_sentences_passage_id'), ['passage_id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('passage_id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('sentence_position', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['textbook_pages.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'passage_id', name='uq_reading_progress')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_passage_id'), ['passage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_passage_id'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('passage_sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passage_sentences_passage_id'))

    op.drop_table('passage_sentences')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_student_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('utterances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utterances_conversation_session_id'))

    op.drop_table('utterances')
    with op.batch_alter_table('passages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passages_lesson_id'))

    op.drop_table('passages')
    with op.batch_alter_table('lesson_page_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_page_links_lesson_id'))

    op.drop_table('lesson_page_links')
    op.drop_table('exercises')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_unit_id'))

    op.drop_table('lessons')
    op.drop_table('conversation_sessions')
    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_student_id'))

    op.drop_table('vocabulary_items')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_course_id'))

    op.drop_table('units')
    with op.batch_alter_table('textbook_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_textbook_pages_sha256'))
        batch_op.drop_index(batch_op.f('ix_textbook_pages_edition_id'))

    op.drop_table('textbook_pages')
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_tasks_student_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_due_at'))

    op.drop_table('review_tasks')
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistakes_subject_id'))
        batch_op.drop_index(batch_op.f('ix_mistakes_student_id'))

    op.drop_table('mistakes')
    with op.batch_alter_table('masteries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masteries_student_id'))
        batch_op.drop_index(batch_op.f('ix_masteries_knowledge_point_id'))

    op.drop_table('masteries')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_learning_sessions_student_id'))

    op.drop_table('learning_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_family_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('textbook_editions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_textbook_editions_subject_id'))

    op.drop_table('textbook_editions')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_family_id'))

    op.drop_table('students')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_subject_id'))

    op.drop_table('knowledge_points')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_family_id'))

    op.drop_table('devices')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_subject_id'))

    op.drop_table('courses')
    op.drop_table('subjects')
    op.drop_table('families')
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_assets_cache_key'))

    op.drop_table('audio_assets')
    # ### end Alembic commands ###

