"use client";
import { FormEvent,useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";

type Settings={provider:"mock"|"dashscope";api_key_configured:boolean;api_key_hint:string;base_url:string;chat_model:string;asr_model:string;tts_model:string;tts_voice:string;tts_url:string};
type Job={id:string;status:string;stage:string;current_package?:string;downloaded_bytes:number;total_bytes:number;result?:Record<string,unknown>;error:string};
type Resources={release:string;packages:{id:string;filename:string;size:number;downloaded:boolean}[];counts:Record<string,number>;latest_job:Job|null};
const allPackages=["data","data_source","textbook_pages","story_images","audio"];

export default function AdminSettings(){
  const qc=useQueryClient();const [message,setMessage]=useState("");
  const settings=useQuery({queryKey:["admin-ai"],queryFn:()=>api<Settings>("/admin/settings/ai"),retry:false});
  const resources=useQuery({queryKey:["admin-resources"],queryFn:()=>api<Resources>("/admin/resources"),refetchInterval:q=>["queued","running"].includes(q.state.data?.latest_job?.status||"")?1500:false,retry:false});
  const save=useMutation({mutationFn:(payload:unknown)=>api<Settings>("/admin/settings/ai",{method:"PUT",body:JSON.stringify(payload)}),onSuccess:()=>{setMessage("AI 配置已保存并立即生效");qc.invalidateQueries({queryKey:["admin-ai"]})},onError:e=>setMessage(e instanceof Error?e.message:"保存失败")});
  const test=useMutation({mutationFn:()=>api<Record<string,{ok?:boolean}|number>>("/admin/settings/ai/test",{method:"POST"}),onSuccess:r=>setMessage(`测试完成：Chat ${typeof r.chat==="object"&&r.chat.ok?"✓":"✗"} · TTS ${typeof r.tts==="object"&&r.tts.ok?"✓":"✗"} · ASR ${typeof r.asr==="object"&&r.asr.ok?"✓":"✗"}`),onError:e=>setMessage(e instanceof Error?e.message:"测试失败")});
  const sync=useMutation({mutationFn:()=>api<Job>("/admin/resources/sync",{method:"POST",body:JSON.stringify({packages:allPackages,acknowledge_copyright:true})}),onSuccess:()=>qc.invalidateQueries({queryKey:["admin-resources"]}),onError:e=>setMessage(e instanceof Error?e.message:"同步启动失败")});
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);save.mutate({provider:data.get("provider"),api_key:data.get("api_key")||null,clear_api_key:data.get("clear_api_key")==="on",base_url:data.get("base_url"),chat_model:data.get("chat_model"),asr_model:data.get("asr_model"),tts_model:data.get("tts_model"),tts_voice:data.get("tts_voice"),tts_url:data.get("tts_url")})}
  if(settings.error)return <section className="feedback bad">需要管理员权限才能访问此页面。</section>;
  return <><h1>系统配置</h1>{message&&<p className="feedback">{message}</p>}<section className="card"><h2>AI Provider</h2>{settings.data&&<form className="stack" onSubmit={submit}><label>供应商<select name="provider" defaultValue={settings.data.provider}><option value="mock">Mock</option><option value="dashscope">百炼 DashScope</option></select></label><label>API Key（当前 {settings.data.api_key_hint||"未配置"}）<input name="api_key" type="password" autoComplete="new-password" placeholder="留空则保持不变"/></label><label className="row"><input className="compact-input" name="clear_api_key" type="checkbox"/>清除现有 API Key</label><label>Chat Base URL<input name="base_url" defaultValue={settings.data.base_url}/></label><label>Chat 模型<input name="chat_model" defaultValue={settings.data.chat_model}/></label><label>ASR 模型<input name="asr_model" defaultValue={settings.data.asr_model}/></label><label>TTS 模型<input name="tts_model" defaultValue={settings.data.tts_model}/></label><label>Emma 音色<input name="tts_voice" defaultValue={settings.data.tts_voice}/></label><label>TTS URL<input name="tts_url" defaultValue={settings.data.tts_url}/></label><div className="row"><button disabled={save.isPending}>保存配置</button><button className="secondary" type="button" disabled={test.isPending} onClick={()=>test.mutate()}>一键测试 Chat → TTS → ASR</button></div></form>}</section><section className="card admin-section"><h2>教材资源</h2><p>固定版本：{resources.data?.release}。同步全部资源约 1.45GB，解压前会检查磁盘空间。</p><div className="stack">{resources.data?.packages.map(p=><div className="row" key={p.id}><strong className="grow">{p.filename}</strong><span>{Math.round(p.size/1024/1024)}MB</span><span>{p.downloaded?"已下载":"未下载"}</span></div>)}</div><ResourceJob job={resources.data?.latest_job} onRefresh={()=>qc.invalidateQueries({queryKey:["admin-resources"]})}/><CopyrightSync onSync={()=>sync.mutate()} disabled={sync.isPending||["queued","running"].includes(resources.data?.latest_job?.status||"")}/><div className="grid">{Object.entries(resources.data?.counts||{}).map(([key,value])=><div className="feedback" key={key}>{key}: {value}</div>)}</div></section></>
}

function CopyrightSync({onSync,disabled}:{onSync:()=>void;disabled:boolean}){const [accepted,setAccepted]=useState(false);return <div className="stack sync-control"><label className="row"><input className="compact-input" type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>我确认拥有展示这些教材内容的合法权利</label><button disabled={disabled||!accepted} onClick={onSync}>一键同步全部资源</button></div>}
function ResourceJob({job,onRefresh}:{job?:Job|null;onRefresh:()=>void}){if(!job)return null;const percent=job.total_bytes?Math.round(job.downloaded_bytes/job.total_bytes*100):0;async function action(kind:"cancel"|"retry"){await api(`/admin/resources/jobs/${job!.id}/${kind}`,{method:"POST"});onRefresh()}return <div className="feedback job-progress"><strong>{job.status} · {job.stage} {job.current_package||""}</strong><p>{percent}%（{Math.round(job.downloaded_bytes/1024/1024)} / {Math.round(job.total_bytes/1024/1024)} MB）</p><progress value={job.downloaded_bytes} max={job.total_bytes||1}/>{job.error&&<p className="bad">{job.error}</p>}{job.status==="completed"&&job.result&&<details><summary>查看本次导入报告</summary><pre>{JSON.stringify(job.result,null,2)}</pre></details>}{["queued","running"].includes(job.status)&&<button className="secondary" onClick={()=>action("cancel")}>取消同步</button>}{["failed","canceled","interrupted"].includes(job.status)&&<button className="secondary" onClick={()=>action("retry")}>重试</button>}</div>}
